# Generated by Django 5.2 on 2025-06-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Name', models.CharField()),
                ('Brand', models.CharField()),
                ('color', models.CharField()),
                ('Milage', models.IntegerField()),
                ('Image', models.ImageField(upload_to='v')),
            ],
        ),
    ]
